config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]
  get '/dashboard', to: 'dashboard#index'
  get '/explore', to: 'explore#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :text, presence: true
  validates :likes, presence: true
  validates :reposts, presence: true

  scope :sorted, -> { order(created_at: :desc) }

  def strftime
    created_at.strftime('%b %d, %Y')
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  validates :email, uniqueness: true, presence: true
  validates :username, presence: true, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, allow_blank: false
  validates :password, confirmation: { case_sensitive: true }

  #dashboard_feed
  def feed
    Post.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize_access
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_access
    return redirect_to root_path, notice: 'Members only! Sign up or login to access that page.' unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authorize_access

  def index
    return not_logged_in_notice unless current_user

    current_user
  end

  private

  def not_logged_in_notice
    flash[:notice] = 'You Must Log In To Visit Your Dashboard'
    redirect_to login_path
  end
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  skip_before_action :authorize_access
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
    
  def create
    post = post_params
    post[:user_id] = current_user.id
    new_post = current_user.posts.new(post)
    if new_post.save
      redirect_to dashboard_path, notice: 'Yo! Nice post!'
    else
      flash[:error] = 'Try again'
      redirect_to dashboard_path
    end
  end

  private

  def post_params
    params[:post][:user_is] = current_user.id
    params.require(:post).permit(:text, :user_id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize_access
  
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      reset_session
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.username}"
      redirect_to dashboard_path
    else
      flash[:error] = 'Please check your credentials and try again!'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Log Out Successful'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize_access

  def new
    @user = User.new
  end

  def create
    new_user = User.new(user_params)
    if new_user.save
      session[:user_id] = new_user.id
      flash[:success] = "Welcome, #{current_user.username}"
      redirect_to dashboard_path
    else
      flash[:error] = 'Your credentials need some work, my friend!'
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params[:user][:email] = params[:user][:email].downcase
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize_access
  
  def index
    redirect_to dashboard_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
Welcome, <%= current_user.username %>!

<section class="stats">
  <%= render 'users/stats' %>
</section>

<section class='posts'>
    <h2>My Posts:</h2>
    
    <%= render partial: '/users/new_post' %>
    
    <ul>
      <% current_user.feed.each do |post| %>
        <li id="post-<%= post.id %>">
          <div><%= post.text %></div> 
          <div><%= post.user.username %></div>
          <div><%= post.strftime %></div>
        </li>
      <% end %>
    </ul>
</section>

app/views/explore/index.html.erb
<% if current_user %>
  <%= link_to 'My Dashboard', dashboard_path %>
<% end %>

<section class='feed'>
    <h2>All Posts:</h2>
    <ul>
      <% @posts.sorted.each do |post| %>
        <li id="post-<%= post.id %>">
          <div><%= post.text %></div> 
          <div><%= post.user.username %></div>
          <div><%= post.strftime %></div>
          <% @user = post.user %>
          <%= render 'users/follow_form' if current_user %>
        </li>
      <% end %>
    </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <main>
      <nav>
        <% if current_user %>
          <%= link_to 'Explore', explore_path %>
          <%= link_to 'Log out', logout_path %>
          <%= link_to 'Dashboard', dashboard_path%>
        <% else %>
          <%= link_to 'Explore', explore_path %>
          <%= link_to 'Register Here', new_user_path %>
          <%= link_to 'Log In', login_path %>
        <% end %>
      </nav>
      <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user==@user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_new_post.html.erb
  <div>
    <% @post = Post.new %>
    <%= form_with model: @post, local: true do |form| %>
      <%= form.text_field :text, id: :text, value: "Enter your message" %>
      <%= form.submit 'Submit Post' %>
    <% end %>
  </div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/new.html.erb
<h1>Create an account!</h1>
<%= form_with model: @user, local: true do |form| %>

  <%= form.label :email, 'Email:' %>
  <%= form.email_field :email, id: :email %>

  <%= form.label :username, 'Username:' %>
  <%= form.text_field :username, id: :username %>

  <%= form.label :password, 'Password:' %>
  <%= form.password_field :password, id: :password %>
  
  <%= form.label :password_confirmation, 'Confirm Password:' %>
  <%= form.password_field :password_confirmation, id: :password_confirmation %>

  <%= form.submit 'Create User' %>
<% end %>

app/views/welcome/index.html.erb
<div id='welcome-container'>
  <h1>Welcome to Tweeter Party</h1>

  <p class='welcome-description'>
    You'll be able to ...
  </p>

  <%= render partial: './sessions/login_form' %>

  <%= link_to 'New to Tweeter? Register Here', new_user_path, id: 'welcome-register-link' %>
</div>